config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  root "welcome#index"

  resources :users, only: [:new, :create, :index]
  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
  end
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :post

  validates :title, presence: true, length: {minimum: 5}

  validates :body, presence: true

  def self.search(term)
    if term == ""
    "You must enter a search term"
    else
    where(["title ILIKE? OR body ILIKE?", "%#{term}%", "%#{term}%"])
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user, except: [:index, :show]

  before_action :find_comment, only: [:edit, :update, :show, :destroy]

  def new
    @comment = Comment.new
  end

  def index
    @comments = Comment.all
  end

  def create
    @post = Post.friendly.find params[:post_id]
    @comment = current_user.comments.new(comment_params)
    @comment.post = @post
    respond_to do |format|
      if @comment.save
        CommentsMailer.notify_post_owner(Comment.last).deliver_later
        format.html {redirect_to post_path(@post), notice: "Your comment was successfuly created."}
        format.js   {render :create_success}
      else
        format.html {redirect_to post_path(@post)}
        format.js   {render :create_failure}
      end
    end
  end

  # def edit
  #
  # end
  #
  # def update
  #   if @comment.update(comment_params)
  #     redirect_to comments_path, alert: "The selected comment was successfully updated."
  #   else
  #     render :edit
  #   end
  # end
  #
  # def show
  #
  # end

  def destroy
    redirect_to root_path, alert: "Access denied: Only the author of a comment or the corresponding post could delete a comment." unless can? :destroy, @comment
    @comment.destroy
    respond_to do |format|
      format.html {redirect_to post_path(@comment.post), notice: "The selected comment was successfully deleted."}
      format.js   {render}
    end
  end


  private

  def find_comment
    @comment = Comment.find params[:id]
  end

  def comment_params
    comment_params = params.require(:comment).permit(:title, :body)
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>">
  <h3 class=""><%= comment.title %></h3>
  <div class="panel panel-default">
      <div class="panel-body">
        <%= comment.body %>
      </div>
  </div>
    <% if can? :destroy, comment %>
      <div>
            <%= link_to "Delete this comment", post_comment_path(@post, comment), method: :delete, class: "btn btn-danger pull-right", data: {confirm: "Are you sure you want to delete this comment?", disable_with: "Deleting..."}, remote: true  %>
      </div>
    <% end %>
</div>
<div class="empty-div">
</div>

app/views/comments/_form.html.erb
<%= simple_form_for [@post, @comment], remote: true do |f| %>
  <div class="form-group">
    <%= f.input :title %>
    <%= f.input :body %>
  </div>
    <%= f.submit "Submit Your Comment", class: "btn btn-primary", data: {disable_with: "Saving..."} %>
<% end %>

app/views/comments/create_failure.js.erb
$("#new_comment").replaceWith("<%= j render 'form' %>");

app/views/comments/create_success.js.erb
$("#comments").prepend("<%= j(render "/comments/comment", comment: @comment) %>");
<% @comment= Comment.new %>
$("#new_comment").replaceWith("<%= j render 'form' %>");

app/views/comments/destroy.js.erb
$("#<%=dom_id(@comment)%>").fadeOut(1500, function(){(this).remove();});