config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  root "welcome#index"

  resources :users, only: [:new, :create, :index]
  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
  end
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user

  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings

  has_many :votes, dependent: :destroy
  has_many :voting_users, through: :votes, source: :user

  validates(:title, {presence: true, length: {minimum: 5}})

  validates(:body, {presence: true})

  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :image, ImageUploader

  paginates_per 24
  max_paginates_per 50

  def liked_by?(user)
    likes_for(user).present?
  end

  def likes_for(user)
    likes.find_by_user_id(user.id)
  end

  def votes_for(user)
    votes.find_by_user_id(user_id)
  end

  def voted_for?(user)
    votes_for(user).present?
  end

  def vote_results
    votes.select{|v| v.is_up?}.count - votes.select{|v| !v.is_up?}.count
  end

  def self.search(term)
    if term
      where(["title ILIKE? OR body ILIKE?", "%#{term}%", "%#{term}%"])
    else
      all
    end
  end






end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user, except: [:show, :index]

  before_action(:find_post, {only: [:show, :edit, :update, :destroy]})

  before_action :authorize, only: [:edit, :update, :destroy]

  def new
    authenticate_user
    @post = Post.new
  end


  def create
    # post_params = params.require(:post).permit(:title, :body)
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to (post_path(id: @post.id))
    else
      render new
    end
  end


  def show
    # @post = Post.find params[:id]
    @comment = Comment.new
  end


  def index
    @query = params[:query]
    if @query
      @posts = Post.order(:created_at).page(params[:page]).search(params[:query])
    else
      @posts = Post.order(:created_at).page(params[:page])
    end
  end


  def edit
    # @post = Post.find params[:id]
      # redirect_to posts_path, alert: "Access denied: Only the author of a post could edit or delete it." unless can? :edit, @post
  end


  def update
    # @post = Post.find params[:id]
    # post_params = params.require(:post).permit(:title, :body)
    if @post.update(post_params)
      flash[:notice] = "Post successfully updated"
      redirect_to post_path(id: @post.id)
    else
      redirect_to edit_post_path(id: @post.id)
    end
  end


  def destroy
    # @post = Post.find params[:id]
    @post.destroy
    flash[:alert] = "Post successfully deleted."
    redirect_to posts_path
  end


  private

  def find_post
    @post = Post.friendly.find params[:id]
  end

  def post_params
    post_params = params.require(:post).permit(:title, :body, {label_ids:[]}, :image)
  end

  def authorize
    redirect_to root_path, alert: "Access denied: Only the author of a post could edit or delete it." unless can? :manage, @post
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <div class="form-group">
    <!-- <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %> -->
    <%= f.input :title %>
  </div>
  <div class="form_group">
    <!-- <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %> -->
    <%= f.input :body %>
  </div>
  <div class="form-group">
    <%= f.input :image %>
  </div>
  <div class="form-group">
    <%= f.association :labels, as: :check_boxes%>
  </div>
  <div class="form-group">
    <%= f.submit({class: "btn btn-primary"})%>
  </div>
<%end  %>

app/views/posts/edit.html.erb
<h3>EDIT THIS POST</h3>
<br>
<p>
  <% if @post.errors.any? %>
  Error:
    <ul>
      <% @post.errors.messages.each do |msg| %>
      <li> <%= msg %></li>
      <% end %>
    </ul>
  <% end %>
</p>
<p>
  Edit this post:
</p>
<%=  render("/posts/form") %>
<!-- <%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <br>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
   <br>
   <%= f.submit %>
<% end %> -->

app/views/posts/index.html.erb
<div class="page-header">
  <h1><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> &nbsp;Posts </h1>
</div>


<div class="row">
  <% @posts.each do |post| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <div class="pull-right"><small>likes: </small><span class="badge"> <%=post.likes.count%> </span> <small>votes: </small> <span class="badge"> <%= post.vote_results %></span> </div>
        <div class="caption">
          <h3><%= post.title %></h3>
          <p>created by: <%= post.user.full_name %></p>
          <p> <%= link_to "Read the Post", post_path(post), class: "btn btn-default"%></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<nav>
    <%= paginate @posts %>
</nav>

app/views/posts/new.html.erb
<div class="page-header">
  <h2><small>SUBMIT A</small> New Post </h2>
</div>

<p>
  <% if @post.errors.any? %>
    <ul>
      Error:
      <% @post.errors.messages.each do |msg| %>
      <li> <%= msg %></li>
      <% end %>
    </ul>
  <% end %>
</p>

<%= render("/posts/form") %>
<!-- <%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <br>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
   <br>
   <%= f.submit %>
<% end %> -->

app/views/posts/show.html.erb
<div class="page-header">
  <h2><small>TITLE:</small> <%= @post.title %> </h2>
  created by: <strong><%= @post.user.full_name %> </strong>
</div>

<div class="empty-div">
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <%= @post.body %>
    <% if @post.image.present? %>
      <span class="pull-right"> <%= image_tag @post.image.url(:small) %> </span>
    <% end %>
  </div>
  <div class="panel-footer"> created on: <%= @post.created_at %> </div>
</div>


<% if @post.labels.any? %>
<div class="">
  Labels: <% @post.labels.each do |l| %>
  <span class="label label-info"> <%= l.name %> </span>&nbsp;
  <% end %>
</div>
<% end %>

<div class="empty-div">
</div>

<p>
<% if can? :edit, @post %>
  <%= link_to "Edit this post", edit_post_path(@post), class: "btn btn-info btn-sm" %>
<% end %>
<% if can? :delete, @post %>
  <%= link_to "Delete this post", post_path(@post), method: :delete, class: "btn btn-danger btn-sm", data: {confirm: "Are you sure you want to delete this post?"} %>
<% end %>
</p>

<div class="empty-div">
</div>

<p>
  <% if user_signed_in? && @post.liked_by?(current_user) %>
    You liked this post! Unlike it?
    <%= link_to fa_icon("thumbs-down"), post_like_path(@post, @post.likes_for(current_user)), method: :delete, class: "btn btn-danger btn-sm" %>
  <% else %>
    Like this post?
    <%= link_to fa_icon("thumbs-up"), post_likes_path(@post), class: "btn btn-info btn-sm", method: :post %>
  <% end %>
    Liked: <%= pluralize(@post.likes.count, "time") %>
</p>

<div class="">
  Votes:
  <% if !user_signed_in? || !@post.voted_for?(current_user) %>
      <%= link_to fa_icon("plus"), post_votes_path(@post, {vote: {is_up: true}}), method: :post %>
      <span class="badge"> <%= @post.vote_results %> </span>
      <%= link_to fa_icon("minus"), post_votes_path(@post, {vote: {is_up: false}}), method: :post %>
  <% elsif @post.votes_for(current_user).is_up? %>
      <%= link_to fa_icon("plus"), post_vote_path(@post, @post.votes_for(current_user)), method: :delete, class: "text-danger" %>
      <span class="badge"> <%= @post.vote_results %> </span>
      <%= link_to fa_icon("minus"), post_vote_path(@post, @post.votes_for(current_user), {vote: {is_up: false}}), method: :patch %>
  <% elsif !@post.votes_for(current_user).is_up? %>
      <%= link_to fa_icon("plus"), post_vote_path(@post, @post.votes_for(current_user), {vote: {is_up: true}}), method: :patch %>
      <span class="badge"> <%= @post.vote_results %> </span>
      <%= link_to fa_icon("minus"), post_vote_path(@post, @post.votes_for(current_user)), method: :delete, class: "text-danger" %>
  <% end %>

<div class="empty-div">
</div>

<%= render "/comments/form" %>

<div class="empty-div">
</div>

<div id="comments">
  <% @post.comments.each do |comment| %>
    <%= render "/comments/comment", comment: comment %>
  <% end %>
</div>