config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  root "welcome#index"

  resources :users, only: [:new, :create, :index]
  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
  end
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    can :manage, Post do |p|
      user == p.user
    end

    can :manage, Comment do |c|
      user == c.user
    end

    can :destroy, Comment do |c|
      user == c.post
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :post

  validates :title, presence: true, length: {minimum: 5}

  validates :body, presence: true

  def self.search(term)
    if term == ""
    "You must enter a search term"
    else
    where(["title ILIKE? OR body ILIKE?", "%#{term}%", "%#{term}%"])
    end
  end

end

app/models/label.rb
class Label < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true

  has_many :labelings, dependent: :destroy
  has_many :labeled_posts, through: :labelings, source: :post

end

app/models/labeling.rb
class Labeling < ActiveRecord::Base
  belongs_to :label
  belongs_to :post
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :post_id, uniqueness: {scope: :user_id}

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user

  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings

  has_many :votes, dependent: :destroy
  has_many :voting_users, through: :votes, source: :user

  validates(:title, {presence: true, length: {minimum: 5}})

  validates(:body, {presence: true})

  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :image, ImageUploader

  paginates_per 24
  max_paginates_per 50

  def liked_by?(user)
    likes_for(user).present?
  end

  def likes_for(user)
    likes.find_by_user_id(user.id)
  end

  def votes_for(user)
    votes.find_by_user_id(user_id)
  end

  def voted_for?(user)
    votes_for(user).present?
  end

  def vote_results
    votes.select{|v| v.is_up?}.count - votes.select{|v| !v.is_up?}.count
  end

  def self.search(term)
    if term
      where(["title ILIKE? OR body ILIKE?", "%#{term}%", "%#{term}%"])
    else
      all
    end
  end






end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  has_many :votes, dependent: :nullify
  has_many :voted_posts, through: :votes, source: :question

  validates :email, presence: true, uniqueness: true

  def full_name
    "#{first_name} #{last_name}".strip
  end


end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :user_id, uniqueness: {scope: :post_id}


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user

  def create
    like = Like.new
    post = Post.friendly.find params[:post_id]
    like.post = post
    like.user = current_user
    if like.save
      redirect_to post_path(post), notice: "You now Like this post. Thanks for liking!"
    else
      redirect_to post_path(post), alert: "You cannot Like a post more than once."
    end
  end

  def destroy
    like = current_user.likes.find_by_id params[:id]
    post = Post.friendly.find_by_id params[:post_id]
    like.destroy
    redirect_to post_path(post), notice: "You have removed your Like form this post."
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user, except: [:show, :index]

  before_action(:find_post, {only: [:show, :edit, :update, :destroy]})

  before_action :authorize, only: [:edit, :update, :destroy]

  def new
    authenticate_user
    @post = Post.new
  end


  def create
    # post_params = params.require(:post).permit(:title, :body)
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to (post_path(id: @post.id))
    else
      render new
    end
  end


  def show
    # @post = Post.find params[:id]
    @comment = Comment.new
  end


  def index
    @query = params[:query]
    if @query
      @posts = Post.order(:created_at).page(params[:page]).search(params[:query])
    else
      @posts = Post.order(:created_at).page(params[:page])
    end
  end


  def edit
    # @post = Post.find params[:id]
      # redirect_to posts_path, alert: "Access denied: Only the author of a post could edit or delete it." unless can? :edit, @post
  end


  def update
    # @post = Post.find params[:id]
    # post_params = params.require(:post).permit(:title, :body)
    if @post.update(post_params)
      flash[:notice] = "Post successfully updated"
      redirect_to post_path(id: @post.id)
    else
      redirect_to edit_post_path(id: @post.id)
    end
  end


  def destroy
    # @post = Post.find params[:id]
    @post.destroy
    flash[:alert] = "Post successfully deleted."
    redirect_to posts_path
  end


  private

  def find_post
    @post = Post.friendly.find params[:id]
  end

  def post_params
    post_params = params.require(:post).permit(:title, :body, {label_ids:[]}, :image)
  end

  def authorize
    redirect_to root_path, alert: "Access denied: Only the author of a post could edit or delete it." unless can? :manage, @post
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
  @user = User.new
end

def create
  user_params = params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  @user = User.new(user_params)
  if @user.save
    session[:user_id] = @user.id
    redirect_to posts_path
  else
    render :new
  end
end

def index
@posts = current_user.posts
@comments = current_user.comments
end


end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_action :authenticate_user

  def create
    # post = Post.find_by_id params[:post_id]
    vote = current_user.votes.new vote_params
    vote.post = post
    if vote.save
      redirect_to post_path(post), notice: "You voted for this post!"
    else
      redirect_to post_path(post), alert: "You can only vote once!"
    end
  end

  def update
    # post = Post.find_by_id params[:post_id]
    vote = current_user.posts.find params[:id]
    if vote.update vote_params
      redirect_to post_path(post), notice: "You have updated your vote."
    else
      redirect_to post_path(post), alert: "Vote was not updated."
    end
  end

  def destroy
    # post = Post.find_by_id params[:post_id]
    vote = current_user.votes.find params[:id]
    vote.destroy
    redirect_to post_path(post), notice: "You have removed your vote!"
  end

  private

  def vote_params
    params.require(:vote).permit(:is_up)
  end

  def post
    @post ||= Post.friendly.find params[:post_id]
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <nav class="navbar navbar-default" style="font-size:14px;">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="<%= root_path %>"><span class='glyphicon glyphicon-home'></span></a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "<span class='glyphicon glyphicon-th-list'></span> All Posts".html_safe, posts_path %></li>
            <li><%= link_to "<span class='glyphicon glyphicon-plus'></span> New Post".html_safe, new_post_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "<span class='glyphicon glyphicon-list'></span> Your Posts + Comments".html_safe, users_path %></li>
            <% end %>
          </ul>
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group" id="search">
              <span class='glyphicon glyphicon-search'></span>
              <%= form_tag posts_path, class: "form-control", method: :get do %>
                <%= label_tag "Search for:" %>
                <%= text_field_tag :query, @query, class:"form-control" %>
                <%= submit_tag "Search", class:"btn btn-default" %>
              <% end %>
            </div>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <% if user_signed_in? %>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <span class='glyphicon glyphicon-user'></span> Hello <%= current_user.first_name %>! <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li> <p class="navbar-text"> <span class='glyphicon glyphicon-log-out'></span> <%= link_to "Sign Out", sessions_path, method: :delete %></p> </li>
              </ul>
              <% else %>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Sign In or Sign Up <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li> <p class="navbar-text"> <span class='glyphicon glyphicon-pencil'></span> <%= link_to "Sign Up", new_user_path %></p> </li>
                <li> <p class="navbar-text"> <span class='glyphicon glyphicon-log-in'></span> <%= link_to "Sign In", new_session_path %></p> </li>
              <% end %>
              </ul>
            </li>
        </ul>
    </nav>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style media="screen">
    .empty-div {
      height: 20px;
    }
    .footer {
      display: inline;
      text-align: center;
      font-size: 10;
      color: #888;
      margin: auto 0;
    }
    #search {
      color: #FFF;
    }
    .jumbotron {
      line-height: 0.85;
      padding-bottom: 100px;
      margin-bottom: 10px;
    }
    .btn-lg {
      width: 250px;
    }
    .half-page {
      display: inline-block;
      width: 40%;
    }
    .dl, .dd {
      display: inline-block;
    }
  </style>
</head>
<body>
  <div class="container">


<%= render "/layouts/nav" %>

  <% if flash[:notice] %>
   <div class="alert alert-success">
     <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
     <%= flash[:notice] %>
   </div>

  <% elsif flash[:alert] %>
   <div class="alert alert-danger">
     <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
     <%= flash[:alert] %>
   </div>
  <% end %>

  <%= yield %>

  </div>






</body>
  <div class="empty-div">
  </div>

  <div class="container footer">
    <p class="center-block">
      <small>created by: kourosh mahvash</small>
    </p>
    <p class="center-block">
      <small><strong>FOR CODECORE BOOTCAMP, OCTOBER 2015 COHORT</strong></small>
    </p>
  </div>
</html>